baseURL = 'https://kasiwacademy.netlify.app/'
languageCode = 'en-us'
title = 'Kasiwa Academy'
theme = 'ananke'

[params]
  description = 'The home of online Secondary Education in Malawi'
  email = 'kasiwaacademy@gmail.com'

[params.contact]
  phone = '+265 999-341-335'
